@extends('layouts.admin')
@section('content')
<div class="admin-page-head">
  <div><span class="eyebrow">TISHLA CONTROL ROOM</span><h1>Good morning, {{ Str::of(auth()->user()->name)->before(' ') }}.</h1><p>Your commerce command centre — sales, orders, stock and customer activity in one view.</p></div>
  <div class="admin-actions"><a class="btn btn-dark" href="{{ route('admin.products.create') }}">NEW PRODUCT</a><a class="btn btn-light" href="{{ route('home') }}" target="_blank" rel="noopener">VIEW STORE ↗</a></div>
</div>
<section class="dashboard-hero"><span class="eyebrow">TISHLA · LIVE COMMERCE PULSE</span><h2>Elegant on the outside.<br>Precise behind the scenes.</h2><p>Use this view to spot what needs attention before opening individual screens.</p><div class="hero-meta"><span class="hero-chip">Today · ₹{{ number_format($todayRevenue,0) }}</span><span class="hero-chip">30-day sales · ₹{{ number_format($revenue30,0) }}</span><span class="hero-chip">Avg. order · ₹{{ number_format($averageOrder,0) }}</span><span class="hero-chip">{{ $pendingOrders }} fulfilment items waiting</span></div></section>
<div class="kpi-grid"><div class="kpi"><span>Active products</span><strong>{{ $activeProducts }}</strong><small>Published to storefront</small></div><div class="kpi"><span>Customers</span><strong>{{ $customers }}</strong><small>Active customer records</small></div><div class="kpi"><span>Orders · 30 days</span><strong>{{ $orders30 }}</strong><small>All order states</small></div><div class="kpi"><span>Revenue · 30 days</span><strong>₹{{ number_format($revenue30,0) }}</strong><small>Valid commerce states</small></div><div class="kpi"><span>Pending fulfilment</span><strong>{{ $pendingOrders }}</strong><small>Needs operational attention</small></div><div class="kpi"><span>Low-stock variants</span><strong>{{ $lowStock }}</strong><small>At or below reorder level</small></div></div>
<div class="analytics-grid"><section class="analytics-card"><div class="section-head"><div><span class="eyebrow">12-MONTH VIEW</span><h2>Revenue rhythm</h2></div><span class="kpi-trend">Monthly sales</span></div>@php $maxRevenue = max($monthlyRevenue ?: [0]); @endphp @if($maxRevenue > 0)<div class="chart-wrap" aria-label="12 month revenue chart">@foreach($monthlyRevenue as $i=>$value) @php $height = max(3, round(($value / $maxRevenue) * 100)); @endphp <div class="chart-bar"><span style="height:{{ $height }}%"></span><small>{{ $monthLabels[$i] }}</small><em class="chart-value">₹{{ number_format($value/1000,1) }}k</em></div>@endforeach</div>@else<div class="empty-chart">Sales history will appear here as orders arrive.</div>@endif</section><section class="analytics-card"><div class="section-head"><div><span class="eyebrow">ORDER FLOW</span><h2>Where orders sit</h2></div></div>@php $maxStatus = max($statusCounts ?: [0]); @endphp<div class="status-list">@forelse($statusCounts as $status=>$count)<div class="status-row"><span>{{ ucwords(str_replace('_',' ',$status)) }}</span><div class="status-track"><div class="status-fill" style="width:{{ $maxStatus ? max(4,round(($count/$maxStatus)*100)) : 0 }}%"></div></div><b>{{ $count }}</b></div>@empty<div class="empty">No orders yet.</div>@endforelse</div></section></div>
<div class="analytics-grid"><section class="analytics-card"><div class="section-head"><div><span class="eyebrow">BEST MOVERS</span><h2>Top products by units</h2></div><a href="{{ route('admin.products.index') }}">Manage catalogue →</a></div><div class="top-products">@forelse($topProducts as $i=>$product)<div class="top-product"><span class="top-product-rank">{{ $i+1 }}</span><div><b>{{ $product->product_name }}</b><small>{{ number_format((int)$product->units) }} units sold</small></div><strong>₹{{ number_format((float)$product->sales,0) }}</strong></div>@empty<div class="empty">Top products will appear after your first orders.</div>@endforelse</div></section><section class="admin-card"><div class="section-head"><div><span class="eyebrow">RECENT ORDERS</span><h2>Commerce at a glance</h2></div><a href="{{ route('admin.orders.index') }}">View all →</a></div>@forelse($recentOrders as $order)<a class="admin-list-row" href="{{ route('admin.orders.show',$order) }}"><span><b>{{ $order->order_number }}</b><small>{{ $order->customer_name }}</small></span><span><b>₹{{ number_format((float)$order->grand_total,0) }}</b><small>{{ str_replace('_',' ',$order->status) }}</small></span></a>@empty<div class="empty">No orders yet.</div>@endforelse</section></div>
<section class="admin-card"><div class="section-head"><div><span class="eyebrow">QUICK ACCESS</span><h2>Operate the store</h2></div></div><div class="shortcut-grid"><a href="{{ route('admin.products.index') }}">Catalogue<small>Products, variants and pricing</small></a><a href="{{ route('admin.orders.index') }}">Orders<small>Payment and fulfilment</small></a><a href="{{ route('admin.customers.index') }}">Customers<small>Retail and wholesale-ready</small></a><a href="{{ route('admin.merchandising.index') }}">Merchandising<small>Homepage and campaigns</small></a><a href="{{ route('admin.media.index') }}">Media Studio<small>Brand and product assets</small></a><a href="{{ route('admin.settings.index') }}">Settings<small>Brand, tax and checkout</small></a></div></section>
@endsection