<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up():void {
  Schema::create('customers',function(Blueprint $t){$t->uuid('id')->primary();$t->string('email',160)->nullable()->index();$t->string('phone',40)->nullable()->index();$t->string('first_name',100);$t->string('last_name',100)->nullable();$t->string('customer_type',30)->default('retail');$t->string('status',30)->default('active');$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('addresses',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('customer_id')->index();$t->string('label',40)->nullable();$t->string('name',120);$t->string('line1',180);$t->string('line2',180)->nullable();$t->string('area',120)->nullable();$t->string('city',100);$t->string('state',100);$t->string('postal_code',30);$t->string('country',80)->default('India');$t->string('phone',40)->nullable();$t->boolean('is_default')->default(false);$t->timestamps();});
  Schema::create('wishlists',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('customer_id')->index();$t->string('name',120)->default('My Wishlist');$t->boolean('is_default')->default(true);$t->timestamps();});
  Schema::create('wishlist_items',function(Blueprint $t){$t->uuid('wishlist_id');$t->uuid('product_id');$t->timestamps();$t->primary(['wishlist_id','product_id']);});
  Schema::create('reviews',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('product_id')->index();$t->unsignedTinyInteger('rating');$t->string('title',160)->nullable();$t->text('body')->nullable();$t->string('status',30)->default('pending');$t->boolean('verified_purchase')->default(false);$t->timestamps();});
  Schema::create('carts',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('customer_id')->nullable()->index();$t->string('session_key',120)->nullable()->index();$t->string('currency',3)->default('INR');$t->timestamps();});
  Schema::create('cart_items',function(Blueprint $t){$t->uuid('cart_id');$t->uuid('variant_id');$t->integer('quantity')->default(1);$t->decimal('unit_price',12,2)->nullable();$t->timestamps();$t->primary(['cart_id','variant_id']);});
  Schema::create('orders',function(Blueprint $t){$t->uuid('id')->primary();$t->string('order_number',40)->unique();$t->uuid('customer_id')->nullable()->index();$t->string('status',30)->default('pending_payment');$t->string('currency',3)->default('INR');$t->decimal('subtotal',14,2)->default(0);$t->decimal('discount_total',14,2)->default(0);$t->decimal('taxable_total',14,2)->default(0);$t->decimal('tax_total',14,2)->default(0);$t->decimal('shipping_total',14,2)->default(0);$t->decimal('grand_total',14,2)->default(0);$t->string('customer_name',160);$t->string('customer_email',160)->nullable();$t->string('customer_phone',40)->nullable();$t->json('billing_address')->nullable();$t->json('shipping_address');$t->text('notes')->nullable();$t->string('source',40)->default('web');$t->string('payment_method',50)->nullable();$t->string('external_payment_reference',160)->nullable();$t->string('external_checkout_reference',160)->nullable();$t->timestamp('placed_at')->nullable();$t->timestamp('confirmed_at')->nullable();$t->timestamp('cancelled_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->timestamps();});
  Schema::create('order_items',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('order_id')->index();$t->uuid('product_id')->nullable();$t->uuid('variant_id')->nullable();$t->string('sku',100);$t->string('product_name',200);$t->string('variant_name',120)->nullable();$t->integer('quantity');$t->decimal('unit_price',12,2);$t->decimal('discount_total',12,2)->default(0);$t->decimal('taxable_total',12,2)->default(0);$t->decimal('tax_rate',5,2)->default(0);$t->decimal('tax_total',12,2)->default(0);$t->decimal('line_total',12,2)->default(0);$t->string('image_url',700)->nullable();$t->timestamps();});
  Schema::create('payments',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('order_id')->index();$t->string('provider',40);$t->string('provider_payment_id',160)->nullable();$t->string('provider_order_id',160)->nullable();$t->decimal('amount',14,2);$t->string('currency',3)->default('INR');$t->string('status',30)->default('pending');$t->string('method',40)->nullable();$t->json('payload')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();});
  Schema::create('shipments',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('order_id')->index();$t->string('provider',80)->nullable();$t->string('tracking_number',160)->nullable();$t->string('label_url',700)->nullable();$t->string('status',40)->default('pending');$t->string('shipping_method',80)->nullable();$t->decimal('shipping_cost',12,2)->default(0);$t->json('payload')->nullable();$t->timestamp('shipped_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->timestamps();});
  Schema::create('returns',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('order_id')->index();$t->string('status',40)->default('requested');$t->text('reason')->nullable();$t->text('resolution')->nullable();$t->decimal('refund_amount',12,2)->nullable();$t->timestamps();});
  Schema::create('coupons',function(Blueprint $t){$t->uuid('id')->primary();$t->string('code',60)->unique();$t->string('discount_type',20);$t->decimal('discount_value',12,2);$t->decimal('min_order_value',12,2)->default(0);$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->boolean('is_active')->default(true);$t->unsignedInteger('usage_limit')->nullable();$t->timestamps();});
  Schema::create('coupon_usages',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('coupon_id');$t->uuid('order_id');$t->uuid('customer_id')->nullable();$t->timestamp('used_at')->useCurrent();$t->timestamps();});
  Schema::create('enquiries',function(Blueprint $t){$t->uuid('id')->primary();$t->string('name',140);$t->string('email',160)->nullable();$t->string('phone',40)->nullable();$t->string('subject',200)->nullable();$t->text('message');$t->string('status',30)->default('new');$t->string('source',40)->default('website');$t->timestamps();});
  Schema::create('order_status_history',function(Blueprint $t){$t->bigIncrements('id');$t->uuid('order_id')->index();$t->string('from_status',40)->nullable();$t->string('to_status',40);$t->text('note')->nullable();$t->uuid('changed_by')->nullable();$t->timestamps();});
 }
 public function down():void{foreach(['order_status_history','enquiries','coupon_usages','coupons','returns','shipments','payments','order_items','orders','cart_items','carts','reviews','wishlist_items','wishlists','addresses','customers'] as $x)Schema::dropIfExists($x);}
};
