<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up():void {
  Schema::create('users',function(Blueprint $t){$t->uuid('id')->primary();$t->string('name',120);$t->string('email',160)->unique();$t->string('password');$t->timestamp('email_verified_at')->nullable();$t->string('role',40)->default('admin');$t->boolean('is_active')->default(true);$t->rememberToken();$t->timestamps();});
  Schema::create('password_reset_tokens',function(Blueprint $t){$t->string('email',160)->primary();$t->string('token');$t->timestamp('created_at')->nullable();});
  Schema::create('departments',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('parent_id')->nullable()->index();$t->string('name',120);$t->string('slug',140)->unique();$t->text('description')->nullable();$t->string('hero_image_url',500)->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('collections',function(Blueprint $t){$t->uuid('id')->primary();$t->string('name',140);$t->string('slug',160)->unique();$t->text('description')->nullable();$t->string('hero_image_url',500)->nullable();$t->string('banner_image_url',500)->nullable();$t->string('collection_type',30)->default('manual');$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_featured')->default(false);$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('products',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('department_id')->nullable()->index();$t->string('sku',80)->unique();$t->string('slug',160)->unique();$t->string('name',200);$t->string('short_description',500)->nullable();$t->longText('description')->nullable();$t->string('fabric',120)->nullable();$t->string('product_type',80)->nullable();$t->string('shoot_type',80)->nullable();$t->decimal('base_price',12,2)->nullable();$t->decimal('gst_rate',5,2)->default(5);$t->string('status',20)->default('draft');$t->boolean('featured')->default(false);$t->unsignedInteger('min_order_qty')->default(1);$t->string('product_badge',80)->nullable();$t->text('care_instructions')->nullable();$t->text('shipping_notes')->nullable();$t->text('fit_notes')->nullable();$t->timestamps();});
  Schema::create('product_variants',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('product_id')->index();$t->string('sku',100)->unique();$t->string('name',120);$t->string('size_name',60)->nullable();$t->string('color_name',80)->nullable();$t->string('color_hex',20)->nullable();$t->decimal('price',12,2)->nullable();$t->decimal('compare_at_price',12,2)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('media_assets',function(Blueprint $t){$t->uuid('id')->primary();$t->string('storage_provider',30)->default('local');$t->string('public_url',700);$t->string('alt_text',220)->nullable();$t->string('mime_type',120)->nullable();$t->unsignedInteger('width')->nullable();$t->unsignedInteger('height')->nullable();$t->unsignedBigInteger('file_size')->nullable();$t->timestamps();});
  Schema::create('product_images',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('product_id')->index();$t->uuid('media_asset_id')->nullable()->index();$t->string('public_url',700)->nullable();$t->string('alt_text',220)->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_primary')->default(false);$t->timestamps();});
  Schema::create('collection_products',function(Blueprint $t){$t->uuid('collection_id');$t->uuid('product_id');$t->unsignedInteger('sort_order')->default(0);$t->primary(['collection_id','product_id']);});
  Schema::create('price_lists',function(Blueprint $t){$t->uuid('id')->primary();$t->string('code',40)->unique();$t->string('name',80);$t->string('customer_type',30)->default('retail');$t->unsignedInteger('priority')->default(100);$t->timestamps();});
  Schema::create('variant_prices',function(Blueprint $t){$t->uuid('price_list_id');$t->uuid('variant_id');$t->decimal('price',12,2);$t->decimal('compare_at_price',12,2)->nullable();$t->primary(['price_list_id','variant_id']);});
  Schema::create('inventory_locations',function(Blueprint $t){$t->uuid('id')->primary();$t->string('code',40)->unique();$t->string('name',120);$t->text('address')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('inventory_stock',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('location_id')->index();$t->uuid('variant_id')->index();$t->integer('on_hand')->default(0);$t->integer('reserved')->default(0);$t->integer('reorder_level')->default(5);$t->timestamps();$t->unique(['location_id','variant_id']);});
  Schema::create('inventory_movements',function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('location_id')->index();$t->uuid('variant_id')->index();$t->string('movement_type',30);$t->integer('quantity');$t->string('reference_type',50)->nullable();$t->uuid('reference_id')->nullable();$t->string('reason',500)->nullable();$t->uuid('created_by')->nullable();$t->timestamps();});
 }
 public function down():void{foreach(['inventory_movements','inventory_stock','inventory_locations','variant_prices','price_lists','collection_products','product_images','media_assets','product_variants','products','collections','departments','password_reset_tokens','users'] as $x)Schema::dropIfExists($x);}
};
